# Generated by Django 6.0.1 on 2026-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture_url_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Uploaded profile picture file', null=True, upload_to='profile_pictures/'),
        ),
    ]
