# Generated by Django 6.0.1 on 2026-02-01 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
        ('workspaces', '0005_workspace_avatar_url_alter_workspace_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('local_file', 'Local File (CSV/Excel)'), ('postgres', 'PostgreSQL Database'), ('mysql', 'MySQL Database'), ('api', 'REST API'), ('google_sheets', 'Google Sheets'), ('stripe', 'Stripe'), ('salesforce', 'Salesforce'), ('shopify', 'Shopify')], max_length=50)),
                ('ownership_scope', models.CharField(choices=[('personal', 'Personal'), ('project', 'Project'), ('workspace', 'Workspace')], max_length=20)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('cached_schema', models.JSONField(blank=True, null=True)),
                ('schema_last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('validation_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_sources', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_data_sources', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='projects.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='datasources.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('use', 'Use in Pipelines'), ('admin', 'Full Admin')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='datasources.datasource')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_data_source_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['owner', 'ownership_scope'], name='datasources_owner_i_93737a_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['project'], name='datasources_project_e3d5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['workspace'], name='datasources_workspa_d7eb59_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['state'], name='datasources_state_2792a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasourcepermission',
            unique_together={('data_source', 'user')},
        ),
    ]
