# Generated by Django 6.0.1 on 2026-01-30 05:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectinvitation_unique_together_and_more'),
        ('workspaces', '0005_workspace_avatar_url_alter_workspace_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['project', '-joined_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='duckdb_path',
            field=models.CharField(blank=True, help_text='Path to DuckDB database file for this project', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='lab_enabled',
            field=models.BooleanField(default=True, help_text='Enable Project Lab for data analysis'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_compute_hours',
            field=models.FloatField(default=10.0, help_text='Maximum compute hours per month', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='max_storage_gb',
            field=models.FloatField(default=5.0, help_text='Maximum storage in GB for datasets', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='sync_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='can_create_datasets',
            field=models.BooleanField(default=False, help_text='Can create new datasets'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='can_execute_pipelines',
            field=models.BooleanField(default=False, help_text='Can run data pipelines in Project Lab'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='can_manage_data_sources',
            field=models.BooleanField(default=False, help_text='Can configure data sources'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', '-updated_at'], name='projects_pr_workspa_e8b93d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['creator', '-updated_at'], name='projects_pr_creator_b54f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectjoinrequest',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_0d708e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectjoinrequest',
            index=models.Index(fields=['user', 'status'], name='projects_pr_user_id_5bdf9f_idx'),
        ),
    ]
