# Generated by Django 6.0.1 on 2026-02-01 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('datasources', '0001_initial'),
        ('projects', '0003_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_dataset_name', models.CharField(max_length=255)),
                ('execution_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('on_demand', 'On Demand')], default='manual', max_length=20)),
                ('schedule_expression', models.CharField(blank=True, help_text='Cron expression for scheduled pipelines', max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('estimated_memory_mb', models.IntegerField(blank=True, null=True)),
                ('estimated_cpu_percent', models.IntegerField(blank=True, null=True)),
                ('estimated_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('estimated_row_count', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=20)),
                ('next_scheduled_run', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='datasources.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('config_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('step_type', models.CharField(choices=[('filter_rows', 'Filter Rows'), ('select_columns', 'Select Columns'), ('rename_column', 'Rename Column'), ('cast_type', 'Cast Type'), ('drop_nulls', 'Drop Nulls'), ('fill_nulls', 'Fill Nulls'), ('drop_duplicates', 'Drop Duplicates'), ('join', 'Join Tables'), ('aggregate', 'Aggregate'), ('custom_sql', 'Custom SQL')], max_length=50)),
                ('step_config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('pipeline_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipelines.pipelineversion')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API')], max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rows_processed', models.IntegerField(blank=True, null=True)),
                ('rows_failed', models.IntegerField(default=0)),
                ('bytes_processed', models.BigIntegerField(blank=True, null=True)),
                ('peak_memory_mb', models.IntegerField(blank=True, null=True)),
                ('peak_cpu_percent', models.IntegerField(blank=True, null=True)),
                ('execution_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('created_dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_executions', to='datasets.datasetversion')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pipelines.pipeline')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL)),
                ('pipeline_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='pipelines.pipelineversion')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['project', '-created_at'], name='pipelines_p_project_7e2261_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['state'], name='pipelines_p_state_808559_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['execution_mode'], name='pipelines_p_executi_212bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['next_scheduled_run'], name='pipelines_p_next_sc_cd5d0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelineversion',
            unique_together={('pipeline', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestep',
            unique_together={('pipeline_version', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['pipeline', '-queued_at'], name='pipelines_p_pipelin_14c8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['state'], name='pipelines_p_state_f74eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['triggered_by'], name='pipelines_p_trigger_52c887_idx'),
        ),
    ]
