# Generated by Django 6.0.1 on 2026-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_remove_workspaceinvitation_workspaces__invitee_25f936_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='External avatar URL', null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Workspace avatar image file', null=True, upload_to='workspace_avatars/'),
        ),
    ]
